export type CountryOption = {
  displayName: string;
  geoName: string;
  flag: string;
  continent: string;
};

export const COUNTRY_CONTINENTS = ["North America", "South America", "Europe", "Asia", "Africa", "Oceania"];

export const COUNTRY_OPTIONS: CountryOption[] = [
  { displayName: "Canada", geoName: "Canada", flag: "🇨🇦", continent: "North America" },
  { displayName: "United States", geoName: "United States of America", flag: "🇺🇸", continent: "North America" },
  { displayName: "Mexico", geoName: "Mexico", flag: "🇲🇽", continent: "North America" },
  { displayName: "Bahamas", geoName: "Bahamas", flag: "🇧🇸", continent: "North America" },
  { displayName: "Belize", geoName: "Belize", flag: "🇧🇿", continent: "North America" },
  { displayName: "Costa Rica", geoName: "Costa Rica", flag: "🇨🇷", continent: "North America" },
  { displayName: "Cuba", geoName: "Cuba", flag: "🇨🇺", continent: "North America" },
  { displayName: "Dominican Republic", geoName: "Dominican Rep.", flag: "🇩🇴", continent: "North America" },
  { displayName: "Guatemala", geoName: "Guatemala", flag: "🇬🇹", continent: "North America" },
  { displayName: "Haiti", geoName: "Haiti", flag: "🇭🇹", continent: "North America" },
  { displayName: "Honduras", geoName: "Honduras", flag: "🇭🇳", continent: "North America" },
  { displayName: "Jamaica", geoName: "Jamaica", flag: "🇯🇲", continent: "North America" },
  { displayName: "Nicaragua", geoName: "Nicaragua", flag: "🇳🇮", continent: "North America" },
  { displayName: "Panama", geoName: "Panama", flag: "🇵🇦", continent: "North America" },
  { displayName: "Puerto Rico", geoName: "Puerto Rico", flag: "🇵🇷", continent: "North America" },
  { displayName: "United States Virgin Islands", geoName: "U.S. Virgin Is.", flag: "🇻🇮", continent: "North America" },
  { displayName: "British Virgin Islands", geoName: "British Virgin Is.", flag: "🇻🇬", continent: "North America" },

  { displayName: "Argentina", geoName: "Argentina", flag: "🇦🇷", continent: "South America" },
  { displayName: "Bolivia", geoName: "Bolivia", flag: "🇧🇴", continent: "South America" },
  { displayName: "Brazil", geoName: "Brazil", flag: "🇧🇷", continent: "South America" },
  { displayName: "Chile", geoName: "Chile", flag: "🇨🇱", continent: "South America" },
  { displayName: "Colombia", geoName: "Colombia", flag: "🇨🇴", continent: "South America" },
  { displayName: "Ecuador", geoName: "Ecuador", flag: "🇪🇨", continent: "South America" },
  { displayName: "Paraguay", geoName: "Paraguay", flag: "🇵🇾", continent: "South America" },
  { displayName: "Peru", geoName: "Peru", flag: "🇵🇪", continent: "South America" },
  { displayName: "Uruguay", geoName: "Uruguay", flag: "🇺🇾", continent: "South America" },
  { displayName: "Venezuela", geoName: "Venezuela", flag: "🇻🇪", continent: "South America" },

  { displayName: "Austria", geoName: "Austria", flag: "🇦🇹", continent: "Europe" },
  { displayName: "Belgium", geoName: "Belgium", flag: "🇧🇪", continent: "Europe" },
  { displayName: "Croatia", geoName: "Croatia", flag: "🇭🇷", continent: "Europe" },
  { displayName: "Czech Republic", geoName: "Czechia", flag: "🇨🇿", continent: "Europe" },
  { displayName: "Denmark", geoName: "Denmark", flag: "🇩🇰", continent: "Europe" },
  { displayName: "England", geoName: "United Kingdom", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", continent: "Europe" },
  { displayName: "Finland", geoName: "Finland", flag: "🇫🇮", continent: "Europe" },
  { displayName: "France", geoName: "France", flag: "🇫🇷", continent: "Europe" },
  { displayName: "Germany", geoName: "Germany", flag: "🇩🇪", continent: "Europe" },
  { displayName: "Greece", geoName: "Greece", flag: "🇬🇷", continent: "Europe" },
  { displayName: "Hungary", geoName: "Hungary", flag: "🇭🇺", continent: "Europe" },
  { displayName: "Iceland", geoName: "Iceland", flag: "🇮🇸", continent: "Europe" },
  { displayName: "Ireland", geoName: "Ireland", flag: "🇮🇪", continent: "Europe" },
  { displayName: "Italy", geoName: "Italy", flag: "🇮🇹", continent: "Europe" },
  { displayName: "Luxembourg", geoName: "Luxembourg", flag: "🇱🇺", continent: "Europe" },
  { displayName: "Netherlands", geoName: "Netherlands", flag: "🇳🇱", continent: "Europe" },
  { displayName: "Norway", geoName: "Norway", flag: "🇳🇴", continent: "Europe" },
  { displayName: "Poland", geoName: "Poland", flag: "🇵🇱", continent: "Europe" },
  { displayName: "Portugal", geoName: "Portugal", flag: "🇵🇹", continent: "Europe" },
  { displayName: "Scotland", geoName: "Scotland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", continent: "Europe" },
  { displayName: "Spain", geoName: "Spain", flag: "🇪🇸", continent: "Europe" },
  { displayName: "Sweden", geoName: "Sweden", flag: "🇸🇪", continent: "Europe" },
  { displayName: "Switzerland", geoName: "Switzerland", flag: "🇨🇭", continent: "Europe" },
  { displayName: "Turkey", geoName: "Turkey", flag: "🇹🇷", continent: "Europe" },
  { displayName: "Vatican City", geoName: "Vatican", flag: "🇻🇦", continent: "Europe" },

  { displayName: "Cambodia", geoName: "Cambodia", flag: "🇰🇭", continent: "Asia" },
  { displayName: "China", geoName: "China", flag: "🇨🇳", continent: "Asia" },
  { displayName: "India", geoName: "India", flag: "🇮🇳", continent: "Asia" },
  { displayName: "Indonesia", geoName: "Indonesia", flag: "🇮🇩", continent: "Asia" },
  { displayName: "Israel", geoName: "Israel", flag: "🇮🇱", continent: "Asia" },
  { displayName: "Japan", geoName: "Japan", flag: "🇯🇵", continent: "Asia" },
  { displayName: "Jordan", geoName: "Jordan", flag: "🇯🇴", continent: "Asia" },
  { displayName: "Malaysia", geoName: "Malaysia", flag: "🇲🇾", continent: "Asia" },
  { displayName: "Philippines", geoName: "Philippines", flag: "🇵🇭", continent: "Asia" },
  { displayName: "Singapore", geoName: "Singapore", flag: "🇸🇬", continent: "Asia" },
  { displayName: "South Korea", geoName: "South Korea", flag: "🇰🇷", continent: "Asia" },
  { displayName: "Thailand", geoName: "Thailand", flag: "🇹🇭", continent: "Asia" },
  { displayName: "United Arab Emirates", geoName: "United Arab Emirates", flag: "🇦🇪", continent: "Asia" },
  { displayName: "Vietnam", geoName: "Vietnam", flag: "🇻🇳", continent: "Asia" },

  { displayName: "Egypt", geoName: "Egypt", flag: "🇪🇬", continent: "Africa" },
  { displayName: "Kenya", geoName: "Kenya", flag: "🇰🇪", continent: "Africa" },
  { displayName: "Morocco", geoName: "Morocco", flag: "🇲🇦", continent: "Africa" },
  { displayName: "South Africa", geoName: "South Africa", flag: "🇿🇦", continent: "Africa" },
  { displayName: "Tanzania", geoName: "Tanzania", flag: "🇹🇿", continent: "Africa" },

  { displayName: "Australia", geoName: "Australia", flag: "🇦🇺", continent: "Oceania" },
  { displayName: "Fiji", geoName: "Fiji", flag: "🇫🇯", continent: "Oceania" },
  { displayName: "New Zealand", geoName: "New Zealand", flag: "🇳🇿", continent: "Oceania" },
  { displayName: "Samoa", geoName: "Samoa", flag: "🇼🇸", continent: "Oceania" },
].sort((a, b) => a.displayName.localeCompare(b.displayName));
